[project]
name = "slurmrestd"
version = "0.0"
requires-python = "==3.12.*"
dependencies = ["ops", "slurmutils"]

[tool.repository]
libraries = [
    "hpc-libs.slurm_ops",
    "operator-libs-linux.apt",
    "operator-libs-linux.systemd",
]
