{
 "title": "Slurm",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "Jobs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Statistics",
   "type": "stat",
   "gridPos": { "h": 6, "w": 5, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max_over_time(slurm_partition_job_state_total{state!~\"RUNNING|PENDING\"}[24h])",
     "legendFormat": "{{state}}"
    }
   ]
  },
  {
   "title": "Active jobs",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 5, "y": 1 },
   "targets": [
    {
     "expr": "slurm_partition_job_state_total{state!~\"COMPLETED|CANCELLED\"}",
     "legendFormat": "{{state}}"
    }
   ]
  },
  { "title": "Resources", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "System metrics",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 5, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "slurm_cpu_load / slurm_cpus_total",
     "legendFormat": "Global CPU load"
    },
    {
     "expr": "slurm_mem_alloc / slurm_mem_real",
     "legendFormat": "Global memory usage"
    }
   ]
  },
  {
   "title": "Scrape info",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 5, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "avg_over_time(slurm_job_scrape_duration[10m])",
     "legendFormat": "Avg. job scrape duration"
    },
    {
     "expr": "avg_over_time(slurm_node_scrape_duration[10m])",
     "legendFormat": "Avg. node scrape duration"
    }
   ]
  },
  {
   "title": "Active alerts",
   "type": "alertlist",
   "gridPos": { "h": 14, "w": 6, "x": 18, "y": 8 },
   "targets": [
    { "expr": "slurm_job", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "CPU count",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 5, "x": 0, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "slurm_cpus_idle{}", "legendFormat": "Idle CPUs" },
    {
     "expr": "slurm_cpus_total - slurm_cpus_idle",
     "legendFormat": "Allocated CPUs"
    },
    {}
   ]
  }
 ]
}