{
 "title": "Slurm",
 "description": "Slurm exporter statistics",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "juju_unit",
    "label": "Juju unit",
    "query": {
     "query": "label_values(slurm_partition_total_cpus{juju_model=~\"$juju_model\",juju_model_uuid=~\"$juju_model_uuid\",juju_application=~\"$juju_application\"},juju_unit)"
    }
   },
   {
    "name": "juju_application",
    "label": "Juju application",
    "query": {
     "query": "label_values(slurm_partition_total_cpus{juju_model=~\"$juju_model\",juju_model_uuid=~\"$juju_model_uuid\"},juju_application)"
    }
   },
   {
    "name": "juju_model_uuid",
    "label": "Juju model uuid",
    "query": {
     "query": "label_values(slurm_partition_total_cpus{juju_model=~\"$juju_model\"},juju_model_uuid)"
    }
   },
   {
    "name": "juju_model",
    "label": "Juju model",
    "query": {
     "query": "label_values(slurm_partition_total_cpus,juju_model)"
    }
   },
   {
    "name": "partition",
    "label": "Partition",
    "query": {
     "query": "label_values(slurm_partition_total_cpus{juju_model_uuid=~\"$juju_model_uuid\", juju_model=~\"$juju_model\", juju_application=~\"$juju_application\", juju_unit=~\"$juju_unit\"}, partition)"
    }
   },
   {
    "name": "jobid",
    "query": {
     "query": "label_values(slurm_proc_cpu_usage{juju_model_uuid=~\"$juju_model_uuid\", juju_model=~\"$juju_model\", juju_application=~\"$juju_application\", juju_unit=~\"$juju_unit\"}, jobid)"
    }
   },
   {
    "name": "state",
    "label": "Job State",
    "query": {
     "query": "query_result(count by (state) (last_over_time(slurm_partition_job_state_total{partition=~\"$partition\", juju_model_uuid=~\"$juju_model_uuid\", juju_model=~\"$juju_model\", juju_application=~\"$juju_application\", juju_unit=~\"$juju_unit\"}[$__range])))"
    }
   },
   {
    "name": "user",
    "label": "User",
    "query": {
     "query": "query_result(count by (username) (last_over_time(slurm_user_state_total{juju_model_uuid=~\"$juju_model_uuid\", juju_model=~\"$juju_model\", juju_application=~\"$juju_application\", juju_unit=~\"$juju_unit\"}[$__range])))"
    }
   },
   {
    "name": "account",
    "label": "Account",
    "query": {
     "query": "query_result(count by (account) (last_over_time(slurm_account_job_state_total{juju_model_uuid=~\"$juju_model_uuid\", juju_model=~\"$juju_model\", juju_application=~\"$juju_application\", juju_unit=~\"$juju_unit\"}[$__range])))"
    }
   }
  ]
 },
 "panels": [
  { "title": "Partition ($partition) Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Partition ($partition) Alloc vs Load",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum by(partition) (slurm_partition_alloc_cpus{partition=~\"$partition\", state=\"allocated\", juju_model_uuid=~\"$juju_model_uuid\", juju_model=~\"$juju_model\", juju_application=~\"$juju_application\", juju_unit=~\"$juju_unit\"}) / sum by(partition) (slurm_partition_total_cpus{partition=~\"$partition\", juju_model_uuid=~\"$juju_model_uuid\", juju_model=~\"$juju_model\", juju_application=~\"$juju_application\", juju_unit=~\"$juju_unit\"})",
     "legendFormat": "{{partition}} cpuA"
    },
    {
     "expr": "sum by(partition) (slurm_partition_alloc_mem{partition=~\"$partition\", state=\"allocated\", juju_model_uuid=~\"$juju_model_uuid\", juju_model=~\"$juju_model\", juju_application=~\"$juju_application\", juju_unit=~\"$juju_unit\"}) / sum by(partition) (slurm_partition_real_mem{partition=~\"$partition\", juju_model_uuid=~\"$juju_model_uuid\", juju_model=~\"$juju_model\", juju_application=~\"$juju_application\", juju_unit=~\"$juju_unit\"})",
     "legendFormat": "{{partition}} memA"
    },
    {
     "expr": "slurm_partition_cpu_load{partition=~\"$partition\", juju_model_uuid=~\"$juju_model_uuid\", juju_model=~\"$juju_model\", juju_application=~\"$juju_application\", juju_unit=~\"$juju_unit\"} / slurm_partition_total_cpus{partition=~\"$partition\", juju_model_uuid=~\"$juju_model_uuid\", juju_model=~\"$juju_model\", juju_application=~\"$juju_application\", juju_unit=~\"$juju_unit\"}",
     "legendFormat": "{{partition}} cpuL"
    }
   ]
  },
  {
   "title": "$state Jobs per Partition ($partition)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "slurm_partition_job_state_total{state=~\"$state\", partition=~\"$partition\", juju_model_uuid=~\"$juju_model_uuid\", juju_model=~\"$juju_model\", juju_application=~\"$juju_application\", juju_unit=~\"$juju_unit\"}",
     "legendFormat": "{{partition}} {{state}}"
    }
   ]
  },
  { "title": "Nodes", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 } },
  {
   "title": "Slurm Node States",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 15 },
   "targets": [
    {
     "expr": "slurm_node_count_per_state{juju_model_uuid=~\"$juju_model_uuid\", juju_model=~\"$juju_model\", juju_application=~\"$juju_application\", juju_unit=~\"$juju_unit\"}",
     "legendFormat": "{{state}}"
    }
   ]
  },
  {
   "title": "Cluster Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "avg(slurm_partition_free_mem{juju_model_uuid=~\"$juju_model_uuid\", juju_model=~\"$juju_model\", juju_application=~\"$juju_application\", juju_unit=~\"$juju_unit\"} / slurm_partition_real_mem{juju_model_uuid=~\"$juju_model_uuid\", juju_model=~\"$juju_model\", juju_application=~\"$juju_application\", juju_unit=~\"$juju_unit\"}) ",
     "legendFormat": "Ave memFree"
    },
    {
     "expr": "avg(slurm_partition_alloc_mem{juju_model_uuid=~\"$juju_model_uuid\", juju_model=~\"$juju_model\", juju_application=~\"$juju_application\", juju_unit=~\"$juju_unit\"} / slurm_partition_real_mem{juju_model_uuid=~\"$juju_model_uuid\", juju_model=~\"$juju_model\", juju_application=~\"$juju_application\", juju_unit=~\"$juju_unit\"})",
     "legendFormat": "Ave memA"
    },
    {
     "expr": "avg(slurm_partition_cpu_load{juju_model_uuid=~\"$juju_model_uuid\", juju_model=~\"$juju_model\", juju_application=~\"$juju_application\", juju_unit=~\"$juju_unit\"} / slurm_partition_total_cpus{juju_model_uuid=~\"$juju_model_uuid\", juju_model=~\"$juju_model\", juju_application=~\"$juju_application\", juju_unit=~\"$juju_unit\"})",
     "legendFormat": "Ave cpuL"
    }
   ]
  },
  { "title": "Account ($account) Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 } },
  {
   "title": "Account ($account) CPU alloc $state",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 13, "x": 0, "y": 34 },
   "targets": [
    {
     "expr": "slurm_account_job_state_cpu_alloc{account=~\"$account\", state=~\"$state\", juju_model_uuid=~\"$juju_model_uuid\", juju_model=~\"$juju_model\", juju_application=~\"$juju_application\", juju_unit=~\"$juju_unit\"}",
     "legendFormat": "{{account}} {{state}}"
    },
    {
     "expr": "sum(slurm_account_job_state_cpu_alloc{juju_model_uuid=~\"$juju_model_uuid\", juju_model=~\"$juju_model\", juju_application=~\"$juju_application\", juju_unit=~\"$juju_unit\"})",
     "legendFormat": "TOTAL ALLOC"
    },
    {
     "expr": "slurm_cpus_total{juju_model_uuid=~\"$juju_model_uuid\", juju_model=~\"$juju_model\", juju_application=~\"$juju_application\", juju_unit=~\"$juju_unit\"}",
     "legendFormat": "TOTAL CPUS"
    }
   ]
  },
  {
   "title": "Account ($account) Mem Alloc",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 11, "x": 13, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "slurm_account_job_state_mem_alloc{account=~\"$account\", juju_model_uuid=~\"$juju_model_uuid\", juju_model=~\"$juju_model\", juju_application=~\"$juju_application\", juju_unit=~\"$juju_unit\"}",
     "legendFormat": "{{account}}"
    },
    {
     "expr": "sum(slurm_account_job_state_mem_alloc{juju_model_uuid=~\"$juju_model_uuid\", juju_model=~\"$juju_model\", juju_application=~\"$juju_application\", juju_unit=~\"$juju_unit\"})",
     "legendFormat": "TOTAL ALLOC"
    },
    {
     "expr": "sum(slurm_mem_real{juju_model_uuid=~\"$juju_model_uuid\", juju_model=~\"$juju_model\", juju_application=~\"$juju_application\", juju_unit=~\"$juju_unit\"})",
     "legendFormat": "TOTAL MEM"
    }
   ]
  },
  {
   "title": "Account ($account) Jobs $state",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 13, "x": 0, "y": 45 },
   "targets": [
    {
     "expr": "slurm_account_job_state_total{state=~\"$state\", account=~\"$account\", juju_model_uuid=~\"$juju_model_uuid\", juju_model=~\"$juju_model\", juju_application=~\"$juju_application\", juju_unit=~\"$juju_unit\"}",
     "legendFormat": "{{account}} {{state}}"
    }
   ]
  },
  { "title": "User Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 56 } },
  {
   "title": "User Totals - RUNNING CPU",
   "type": "timeseries",
   "description": "Total CPUS that are in the state RUNNING",
   "gridPos": { "h": 16, "w": 24, "x": 0, "y": 57 },
   "targets": [
    {
     "expr": "slurm_user_cpu_alloc{state=\"RUNNING\", username=~\"($user|${__user.login})\", juju_model_uuid=~\"$juju_model_uuid\", juju_model=~\"$juju_model\", juju_application=~\"$juju_application\", juju_unit=~\"$juju_unit\"}",
     "legendFormat": "{{username}}"
    }
   ]
  },
  { "title": "Job Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 73 } },
  {
   "title": "Tracked Usage %",
   "type": "timeseries",
   "gridPos": { "h": 19, "w": 12, "x": 0, "y": 74 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "slurm_proc_cpu_usage{juju_model_uuid=~\"$juju_model_uuid\", juju_model=~\"$juju_model\", juju_application=~\"$juju_application\", juju_unit=~\"$juju_unit\"} / on(jobid) group_right() slurm_job_cpu_alloc{juju_model_uuid=~\"$juju_model_uuid\", juju_model=~\"$juju_model\", juju_application=~\"$juju_application\", juju_unit=~\"$juju_unit\"}",
     "legendFormat": "{{jobid}} cpu usage %"
    },
    {
     "expr": "slurm_proc_mem_usage{juju_model_uuid=~\"$juju_model_uuid\", juju_model=~\"$juju_model\", juju_application=~\"$juju_application\", juju_unit=~\"$juju_unit\"} / on(jobid) group_right() (slurm_job_mem_alloc{juju_model_uuid=~\"$juju_model_uuid\", juju_model=~\"$juju_model\", juju_application=~\"$juju_application\", juju_unit=~\"$juju_unit\"} * 1000)",
     "legendFormat": "{{jobid}} mem usage %"
    }
   ]
  },
  {
   "title": "Read/Write bytes",
   "type": "timeseries",
   "gridPos": { "h": 19, "w": 12, "x": 12, "y": 74 },
   "targets": [
    {
     "expr": "rate(slurm_proc_read_bytes{juju_model_uuid=~\"$juju_model_uuid\", juju_model=~\"$juju_model\", juju_application=~\"$juju_application\", juju_unit=~\"$juju_unit\"}[$__rate_interval])",
     "legendFormat": "{{jobid}} read_bytes"
    },
    {
     "expr": "rate(slurm_proc_write_bytes{juju_model_uuid=~\"$juju_model_uuid\", juju_model=~\"$juju_model\", juju_application=~\"$juju_application\", juju_unit=~\"$juju_unit\"}[$__rate_interval])",
     "legendFormat": "{{jobid}} write_bytes"
    }
   ]
  },
  {
   "title": "Usage vs Alloc (Mem) for jobid: $jobid",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 93 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "slurm_proc_mem_usage{jobid=\"$jobid\", juju_model_uuid=~\"$juju_model_uuid\", juju_model=~\"$juju_model\", juju_application=~\"$juju_application\", juju_unit=~\"$juju_unit\"}",
     "legendFormat": "{{jobid}} usage"
    },
    {
     "expr": "slurm_job_mem_alloc{jobid=\"$jobid\", juju_model_uuid=~\"$juju_model_uuid\", juju_model=~\"$juju_model\", juju_application=~\"$juju_application\", juju_unit=~\"$juju_unit\"}",
     "legendFormat": "{{jobid}} alloc"
    }
   ]
  },
  {
   "title": "Usage vs Alloc (Cpu) for jobid: $jobid",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 93 },
   "targets": [
    {
     "expr": "slurm_proc_cpu_usage{jobid=\"$jobid\", juju_model_uuid=~\"$juju_model_uuid\", juju_model=~\"$juju_model\", juju_application=~\"$juju_application\", juju_unit=~\"$juju_unit\"}",
     "legendFormat": "{{jobid}} usage"
    },
    {
     "expr": "slurm_job_cpu_alloc{jobid=\"$jobid\", juju_model_uuid=~\"$juju_model_uuid\", juju_model=~\"$juju_model\", juju_application=~\"$juju_application\", juju_unit=~\"$juju_unit\"}*100",
     "legendFormat": "{{jobid}} alloc"
    }
   ]
  },
  { "title": "Slurmctld Diagnostics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 105 } },
  {
   "title": "RPC Count Per Message Type per $__interval",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 106 },
   "targets": [
    {
     "expr": "rate(slurm_rpc_msg_type_count{juju_model_uuid=~\"$juju_model_uuid\", juju_model=~\"$juju_model\", juju_application=~\"$juju_application\", juju_unit=~\"$juju_unit\"}[$__rate_interval])",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "RPC Count Per User per $__interval",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 106 },
   "targets": [
    {
     "expr": "rate(slurm_rpc_user_count{juju_model_uuid=~\"$juju_model_uuid\", juju_model=~\"$juju_model\", juju_application=~\"$juju_application\", juju_unit=~\"$juju_unit\"}[$__rate_interval])",
     "legendFormat": "{{user}}"
    }
   ]
  },
  {
   "title": "Avg Time per RPC per MSG",
   "type": "timeseries",
   "description": "Only show latencies above 100 microseconds (1 ms)",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 114 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "rate(slurm_rpc_msg_type_avg_time{juju_model_uuid=~\"$juju_model_uuid\", juju_model=~\"$juju_model\", juju_application=~\"$juju_application\", juju_unit=~\"$juju_unit\"}[$__rate_interval])",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Avg Time per RPC per User",
   "type": "timeseries",
   "description": "Only show latencies above 100 microseconds (1 ms)",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 114 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "(rate(slurm_rpc_user_total_time{juju_model_uuid=~\"$juju_model_uuid\", juju_model=~\"$juju_model\", juju_application=~\"$juju_application\", juju_unit=~\"$juju_unit\"}[$__rate_interval]) / on(user) rate(slurm_rpc_user_count{juju_model_uuid=~\"$juju_model_uuid\", juju_model=~\"$juju_model\", juju_application=~\"$juju_application\", juju_unit=~\"$juju_unit\"}[$__rate_interval])) > 100",
     "legendFormat": "{{user}}"
    }
   ]
  },
  {
   "title": "Msg Type Summary",
   "type": "piechart",
   "description": "Percentage load per Msg Type",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 122 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(slurm_rpc_msg_type_count{juju_model_uuid=~\"$juju_model_uuid\", juju_model=~\"$juju_model\", juju_application=~\"$juju_application\", juju_unit=~\"$juju_unit\"}[$__rate_interval])",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Top 25 Users",
   "type": "piechart",
   "description": "Top 25 Users by RPC Count",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 122 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(25, rate(slurm_rpc_user_count{juju_model_uuid=~\"$juju_model_uuid\", juju_model=~\"$juju_model\", juju_application=~\"$juju_application\", juju_unit=~\"$juju_unit\"}[$__rate_interval]))",
     "legendFormat": "{{user}}"
    }
   ]
  },
  { "title": "Exporter Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 130 } },
  {
   "title": "Exporter Mem Usage",
   "type": "timeseries",
   "description": "Number of bytes allocated and in use",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 131 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "go_memstats_alloc_bytes{job=~\".*default\", juju_model_uuid=~\"$juju_model_uuid\", juju_model=~\"$juju_model\", juju_application=~\"$juju_application\", juju_unit=~\"$juju_unit\"}",
     "legendFormat": "{{juju_unit}}"
    }
   ]
  },
  {
   "title": "Scrape Errors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 131 },
   "targets": [
    {
     "expr": "rate(slurm_job_scrape_error{juju_model_uuid=~\"$juju_model_uuid\", juju_model=~\"$juju_model\", juju_application=~\"$juju_application\", juju_unit=~\"$juju_unit\"}[$__rate_interval])",
     "legendFormat": "job scrape error"
    },
    {
     "expr": "rate(slurm_node_scrape_error{juju_model_uuid=~\"$juju_model_uuid\", juju_model=~\"$juju_model\", juju_application=~\"$juju_application\", juju_unit=~\"$juju_unit\"}[$__rate_interval])",
     "legendFormat": "node scrape error"
    },
    {
     "expr": "rate(slurm_diag_scrape_error{juju_model_uuid=~\"$juju_model_uuid\", juju_model=~\"$juju_model\", juju_application=~\"$juju_application\", juju_unit=~\"$juju_unit\"}[$__rate_interval])",
     "legendFormat": "diag scrape error"
    }
   ]
  },
  {
   "title": "Exporter cli scrape duration",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 139 },
   "fieldConfig": { "defaults": { "unit": "dtdurationms" } },
   "targets": [
    {
     "expr": "slurm_node_scrape_duration{juju_model_uuid=~\"$juju_model_uuid\", juju_model=~\"$juju_model\", juju_application=~\"$juju_application\", juju_unit=~\"$juju_unit\"}",
     "legendFormat": "sinfo cli duration"
    },
    {
     "expr": "slurm_job_scrape_duration{juju_model_uuid=~\"$juju_model_uuid\", juju_model=~\"$juju_model\", juju_application=~\"$juju_application\", juju_unit=~\"$juju_unit\"}",
     "legendFormat": "squeue cli duration"
    },
    {
     "expr": "slurm_diag_scrape_duration{juju_model_uuid=~\"$juju_model_uuid\", juju_model=~\"$juju_model\", juju_application=~\"$juju_application\", juju_unit=~\"$juju_unit\"}",
     "legendFormat": "sdiag scrape duration"
    }
   ]
  }
 ]
}