name: Pull Request Backporting using Git Backporting

on:
  pull_request_target:
    types:
      - closed
      - labeled
    branches:
      - main

permissions:
  contents: write # so it can comment
  pull-requests: write # so it can create pull requests

jobs:
  backport:
    uses: charmed-hpc/.github/.github/workflows/backport.yaml@main
    with:
      branches: '["track/25.11"]'
    secrets: inherit
